import { mount } from 'svelte'
import './app.css'
import App from './App.svelte'

// Find the target element. 
// Ideally passed via data attribute or found within a specific context.
// For SDC, we might look for a specific class or ID generated by the backend.
const target = document.querySelector('.svelte-component-root[data-component="test_component"]');

if (target) {
  const propsStr = target.getAttribute('data-props');
  const props = propsStr ? JSON.parse(propsStr) : {};

  mount(App, {
    target: target,
    props: props
  })
}
